.TH LPDF 1 spdf
.SH NAME
spdf \- little pdf viewer
.SH SYNOPSIS
.B spdf
.RB [ \-w
.IR window ]
.RI pdf_file
.SH DESCRIPTION
.B spdf
is a small pdf viewer based on poppler and Xlib
.SH OPTIONS
.TP
.BI \-w " window"
embeds spdf within the window identified by
.I window
.SH SHORTCUTS
.TP
.B [Ctrl-|Alt-]q or Esc
Quit spdf.
.TP
.B [Ctrl-|Alt-]r
Reload document.
.TP
.B Ctrl-Page Up
Show previous page.
.TP
.B Ctrl-Page Down
Show next page.
.TP
.B Ctrl-Home
Show first page.
.TP
.B Ctrl-End
Show last page.
.TP
.B z
Fit page (default).
.TP
.B w
Fit page width.
.TP
.B Up or Page Up
Scroll up (small or large scroll).
.TP
.B Down or Page Down
Scroll down (small or large scroll).
.TP
.B b
Go back to previous location (after clicking a link).
.TP
.B Ctrl-c
Copy selected text to clipboard. On mouse selection, spdf copies text to primary selection.
.I Ctrl-c
copies that to clipboard selection.
.TP
.B [Ctrl-|Alt-]g
Goto page.
.TP
.B [Ctrl-|Alt-]s or /
Search text. Append '?' to search backwards or '~' to search case-insensitive. Or both flags at the same time.
.TP
.B p
Show current page number.
.TP
.B m
Magnify current selection.
.TP
.B [
Rotate page clockwise.
.TP
.B ]
Rotate page counterclockwise.
.TP
.B Esc (in command mode)
Exit to normal mode.
.SH CUSTOMIZATION
.B spdf
can be customized by creating custom config.h and recompiling.
.SH COPYRIGHT
.B spdf
is free software, comes without any warranty and is licensed under Do What The Fuck You Want To Public License, Version 2.
.SH AUTHOR
Łukasz Krotowski (https://lkrotowski.com)
